name: GitHub Pages デプロイ

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      # 依存関係をインストール
      - name: Install dependencies
        working-directory: stem-com
        run: npm install --force

      # 環境変数の注入
      - name: Inject environment variables
        working-directory: stem-com
        run: |
          echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> .env
          echo "REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}" >> .env
          echo "REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }}" >> .env
          echo "REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }}" >> .env
          echo "REACT_TOKEN=${{ secrets.REACT_TOKEN }}" >> .env
          echo "REACT_TOKEN2=${{ secrets.REACT_TOKEN2 }}" >> .env

      # プロジェクトのビルド
      - name: Build the project
        working-directory: stem-com
        run: npm build

      # GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REACT_GITHUB_TOKEN }}
          publish_dir: stem-com/dist
